version: '3.9'
services:

  openhab:
    container_name: OpenHAB
    image: openhab/openhab:4.1.0-debian
    restart: unless-stopped
    network_mode: host
    group_add:
      - tty
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - ./ssh:/openhab/.ssh
      - ./addons:/openhab/addons
      - ./conf:/openhab/conf
      - ./userdata:/openhab/userdata
      
    environment:
      - CRYPTO_POLICY=unlimited
      - EXTRA_JAVA_OPTS=${EXTRA_JAVA_OPTS} 
